### PR TITLE
Optimized code

### PR DESCRIPTION
**Pull request by gengyoubo**
Added "you put" localization key
Optimized the code of "you put".
(can be copied)

### CODE REVIEW

**Comment by Foxyas** [comment]
i use the code and i fix a few issues with the "zh_ch" the "// TEXT" only work with java and the lang files use JSON [Java Script] and the annotations with "// text" don't exist in JSON

**Comment by Foxyas** [comment]
and the pat feature don't work with both heads when is a "non Special or Patable entity"

**Comment by Foxyas** [comment]
but i fix all

**Comment by gengyoubo** [comment]
What about localization keys?

**Comment by Foxyas** [comment]
> What about localization keys?

Already was in the plans But you help me with that alop :P

**Comment by Foxyas** [comment]
Btw is key.changed_addon not key.changedaddon

**Pull request closed without merging**
